# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inspection_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# pylint: disable=all

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal, QObject


class Ui_InspectionWindow(object):
    def setupUi(self, InspectionWindow):
        InspectionWindow.setObjectName("InspectionWindow")
        InspectionWindow.resize(self.screen_widht, self.screen_height)
        self.centralwidget = QtWidgets.QWidget(InspectionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.qframe_image = QtWidgets.QFrame(self.centralwidget)
        self.qframe_image.setGeometry(
            QtCore.QRect(
                10, 60,
                self.main_image_width,
                self.main_image_height
            )
        )
        self.qframe_image.setFrameShape(QtWidgets.QFrame.Box)
        self.qframe_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.qframe_image.setObjectName("frame")
        
        self.widget_image = QtWidgets.QWidget(self.qframe_image)
        self.label = QtWidgets.QLabel(self.widget_image)
        self.label.setFixedSize(self.main_image_width, self.main_image_height)

        self.lbl_camera_image_txt = QtWidgets.QLabel(self.centralwidget, text="IMAGEM DA CÂMERA")
        self.lbl_camera_image_txt.setFont(QtGui.QFont("Arial", 14, weight=QtGui.QFont.Bold))
        self.lbl_camera_image_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_camera_image_txt.setGeometry(
            QtCore.QRect(
                10, 10, self.main_image_width, 50
            )
        )
        self.lbl_camera_image_txt.setObjectName("lbl_camera_image_txt")

        self.btn_start_camera = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start_camera.setGeometry(
            QtCore.QRect(
                (self.main_image_width//4)-210,
                self.main_image_height+70,
                200, 50
            )
        )
        self.btn_start_camera.setObjectName("btn_start_camera")

        self.btn_stop_camera = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop_camera.setGeometry(
            QtCore.QRect(
                ((self.main_image_width//4)*2)-210,
                self.main_image_height+70,
                200, 50
            )
        )
        self.btn_stop_camera.setObjectName("btn_stop_camera")

        self.btn_capturar_imagem = QtWidgets.QPushButton(self.centralwidget)
        self.btn_capturar_imagem.setGeometry(
            QtCore.QRect(
                ((self.main_image_width//4)*3)-210,
                self.main_image_height+70,
                200, 50
            )
        )
        self.btn_capturar_imagem.setObjectName("btn_capturar_imagem")

        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(
            QtCore.QRect(
                self.main_image_width-210,
                self.main_image_height+70,
                200, 50
            )
        )
        self.btn_back.setObjectName("btn_back")

        self.qframe_for_list = QtWidgets.QFrame(self.centralwidget)
        self.qframe_for_list.setGeometry(
            QtCore.QRect(
                self.main_image_width+10,
                60,
                self.main_image_width-20,
                self.main_image_height
            )
        )
        self.qframe_for_list.setFrameShape(QtWidgets.QFrame.Box)
        self.qframe_for_list.setFrameShadow(QtWidgets.QFrame.Raised)
        self.qframe_for_list.setObjectName("frame")

        self.lbl_results_txt = QtWidgets.QLabel(self.centralwidget, text="INFORMAÇÕES DE RESULTADO")
        self.lbl_results_txt.setFont(QtGui.QFont("Arial", 14, weight=QtGui.QFont.Bold))
        self.lbl_results_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_results_txt.setGeometry(
            QtCore.QRect(
                self.main_image_width+10, 10, self.main_image_width-20, 50
            )
        )
        self.lbl_results_txt.setObjectName("lbl_results_txt")

        self.list_box = QtWidgets.QVBoxLayout(self)
        self.qframe_for_list.setLayout(self.list_box)

        self.header_widget = QtWidgets.QWidget()
        self.header_layout = QtWidgets.QHBoxLayout()
        self.lbl_name = QtWidgets.QLabel("Identificador")
        self.lbl_name.setFont(QtGui.QFont("Arial", 14))
        self.lbl_img_input = QtWidgets.QLabel("Img. de entrada")
        self.lbl_img_input.setFont(QtGui.QFont("Arial", 14))
        self.lbl_img_output = QtWidgets.QLabel("Img. de saída")
        self.lbl_img_output.setFont(QtGui.QFont("Arial", 14))
        self.lbl_result = QtWidgets.QLabel("Resultado")
        self.lbl_result.setFont(QtGui.QFont("Arial", 14))
        self.header_layout.addWidget(self.lbl_name)
        self.header_layout.addWidget(self.lbl_img_input)
        self.header_layout.addWidget(self.lbl_img_output)
        self.header_layout.addWidget(self.lbl_result)
        self.header_widget.setLayout(self.header_layout)
        self.list_box.addWidget(self.header_widget)

        self.scroll = QtWidgets.QScrollArea(self)
        self.scroll.horizontalScrollBar().setEnabled(False);
        self.list_box.addWidget(self.scroll)
        self.scroll.setWidgetResizable(True)
        self.scrollContent = QtWidgets.QWidget(self.scroll)

        self.scrollLayout = QtWidgets.QVBoxLayout(self.scrollContent)
        self.scrollContent.setLayout(self.scrollLayout)
        self.scroll.setWidget(self.scrollContent)

        InspectionWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(InspectionWindow)
        self.statusbar.setObjectName("statusbar")
        InspectionWindow.setStatusBar(self.statusbar)

        self.retranslateUi(InspectionWindow)
        QtCore.QMetaObject.connectSlotsByName(InspectionWindow)
        
        SrcSize = QtGui.QScreen.availableGeometry(QtWidgets.QApplication.primaryScreen())
        frmX = (SrcSize.width() - InspectionWindow.width())//2
        frmY = (SrcSize.height() - InspectionWindow.height())//2
        InspectionWindow.move(frmX, frmY)

    def retranslateUi(self, InspectionWindow):
        _translate = QtCore.QCoreApplication.translate
        InspectionWindow.setWindowTitle(_translate("InspectionWindow", "PCB_Inspection-0.1.0"))
        self.btn_start_camera.setText(_translate("InspectionWindow", "Iniciar câmera"))
        self.btn_stop_camera.setText(_translate("InspectionWindow", "Parar câmera"))
        self.btn_capturar_imagem.setText(_translate("InspectionWindow", "Capturar imagem"))
        self.btn_back.setText(_translate("InspectionWindow", "Voltar"))
        self.setWindowFlag(QtCore.Qt.FramelessWindowHint)