# pylint: disable=all

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listuserwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(self.screen_widht, self.screen_height)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gpbox_user_list = QtWidgets.QGroupBox(self.centralwidget)
        self.gpbox_user_list.setGeometry(
            QtCore.QRect(
                10, 10,
                int(self.screen_widht*0.85),
                int(self.screen_height*0.90)
            )
        )
        self.gpbox_user_list.setObjectName("gpbox_user_list")
        self.table_board_list = QtWidgets.QTableWidget(self.gpbox_user_list)
        self.table_board_list.setGeometry(
            QtCore.QRect(
                10,
                30,
                int(self.gpbox_user_list.size().width()-20),
                int(self.gpbox_user_list.size().height()-40))
        )
        self.table_board_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_board_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_board_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.table_board_list.setObjectName("table_board_list")
        self.table_board_list.setColumnCount(5)
        self.table_board_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_board_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_board_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_board_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_board_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_board_list.setHorizontalHeaderItem(4, item)
        self.table_board_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_board_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_board_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        
        self.btn_change_status = QtWidgets.QPushButton(self.centralwidget)
        self.btn_change_status.setGeometry(QtCore.QRect(self.screen_widht-100, 40, 90, 50))
        self.btn_change_status.setObjectName("btn_change_status")
        self.btn_run_inspection = QtWidgets.QPushButton(self.centralwidget)
        self.btn_run_inspection.setGeometry(QtCore.QRect(self.screen_widht-100, 100, 90, 50))
        self.btn_run_inspection.setObjectName("btn_run_inspection")
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(self.screen_widht-100, 160, 90, 50))
        self.btn_close.setObjectName("btn_close")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        SrcSize = QtGui.QScreen.availableGeometry(QtWidgets.QApplication.primaryScreen())
        frmX = (SrcSize.width() - MainWindow.width())//2
        frmY = (SrcSize.height() - MainWindow.height())//2
        MainWindow.move(frmX, frmY)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gpbox_user_list.setTitle(_translate("MainWindow", "Lista de placas"))
        item = self.table_board_list.horizontalHeaderItem(0)
        self.table_board_list.horizontalHeader().setMinimumSectionSize(
            int((self.gpbox_user_list.size().width()//5)*0.96)
        )
        item.setText(_translate("MainWindow", "Identificador da placa"))
        item = self.table_board_list.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Aprovadas"))
        item = self.table_board_list.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Reprovadas"))
        item = self.table_board_list.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Total"))
        item = self.table_board_list.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        self.btn_change_status.setText(_translate("MainWindow", "Modificar\nStatus"))
        self.btn_run_inspection.setText(_translate("MainWindow", "Iniciar\nInspeção"))
        self.btn_close.setText(_translate("MainWindow", "Sair"))
        self.setWindowFlag(QtCore.Qt.FramelessWindowHint)